### ISSUE TITLE
loss of YAGO.RotatE file 

### ISSUE THREAD

**Issue by hide-on-bush-c** [yy-ko/khan#2]
Hello, I would like to express my gratitude for the valuable research work you have done, which has been of great help to my project.
While attempting to replicate your work, I noticed that some key files appear to be missing, including YAGO.RotatE under ./pre-trained. Therefore, I would like to inquire whether you might be able to provide these files. Once again, thank you for your work and assistance.

**Comment by yy-ko** [comment]
Thank you for your attention to our work.

Due to the file size, we provided all the pre-trained KG embeddings in the external link (Datasets -> 3. Pre-trained KG embeddings in the ReadMe): 
https://drive.google.com/drive/u/2/folders/14EgeI1RdSTccETqRgDd36writP6lUu1R

Feel free to let me know if there's other issues.
